services:
  alerts:
    path: src/services/alerts
  mmdl:
    path: src/services/mmdl
  seatool:
    path: src/services/seatool
  status:
    path: src/services/status
  compare:
    dependsOn: alerts
    path: src/services/compare
    params:
      mmdlTableName: ${mmdl.TableName}
      mmdlTableArn: ${mmdl.TableArn}
      mmdlTableStreamArn: ${mmdl.TableStreamArn}
      seatoolTableName: ${seatool.TableName}
      seatoolTableArn: ${seatool.TableArn}
      statusTableName: ${status.TableName}
      statusTableArn: ${status.TableArn}
      sesLogGroupArn: ${alerts.SesLogGroupArn}
      sesLogGroupName: ${alerts.SesLogGroupName}
      errorsTopicArn: ${alerts.ErrorsTopicArn}
  connector:
    path: src/services/connector
    params:
      mmdlTableName: ${mmdl.TableName}
      mmdlTableArn: ${mmdl.TableArn}
      mmdlTableStreamArn: ${mmdl.TableStreamArn}
      seatoolTableName: ${seatool.TableName}
      seatoolTableArn: ${seatool.TableArn}
      alarmsTopicArn: ${alerts.AlarmsTopicArn}
