service: ${self:custom.project}-compare-mmdl

frameworkVersion: "3"

package:
  individually: true

plugins:
  - serverless-stack-termination-protection
  - "@stratiformdigital/serverless-s3-security-helper"
  - "@stratiformdigital/serverless-online"
  - "@stratiformdigital/serverless-iam-helper"
  - serverless-step-functions
  - serverless-esbuild

provider:
  name: aws
  runtime: nodejs18.x
  region: ${env:REGION_A}
  stackTags:
    PROJECT: ${self:custom.project}
    SERVICE: ${self:service}
  iam:
    role:
      path: /delegatedadmin/developer/
      permissionsBoundary: arn:aws:iam::${aws:accountId}:policy/cms-cloud-admin/developer-boundary-policy
      statements:
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:Scan
          Resource:
            - ${param:mmdlTableArn}
            - ${param:seatoolTableArn}
        - Effect: Allow
          Action:
            - sns:Publish
          Resource:
            - ${param:errorsTopicArn}
        - Effect: Allow
          Action:
            - states:StartExecution
          Resource:
            - !Ref MMDLAlertingStateMachine
            - !Sub "arn:aws:states:${self:provider.region}:${AWS::AccountId}:execution:${MMDLAlertingStateMachine.Name}:*"
        - Effect: Allow
          Action:
            - ses:SendEmail
            - ses:SendRawEmail
          Resource:
            - !Sub "arn:aws:ses:${self:provider.region}:${AWS::AccountId}:identity/*"
        - Effect: Allow
          Action:
            - secretsmanager:GetSecretValue
          Resource:
            - !Sub "arn:aws:secretsmanager:${self:provider.region}:${AWS::AccountId}:secret:${self:custom.project}/${sls:stage}/mmdl-alerts*"
        - Effect: Allow
          Action:
            - secretsmanager:ListSecrets
          Resource: "*"
        - Effect: Allow
          Action:
            - logs:PutLogEvents
            - logs:GetLogEvents
          Resource:
            - ${param:sesLogGroupArn}
        - Effect: Allow
          Action:
            - states:ListExecutions
            - states:StopExecution
          Resource: "*"
        - Effect: Allow
          Action:
            - kms:GenerateDataKey
            - kms:Decrypt
          Resource:
            - !Sub "arn:aws:kms:${self:provider.region}:${AWS::AccountId}:key/*"
params:
  master:
    initialWaitSec: 172800 # 2 days
    tempWaitSec: 172800 # 2 days
    signedSinceChoiceSec: 345600 # 4 days
    recordAgeChoiceSec: 21686400 # 251 days
    workflowsStatus: ON
  val:
    initialWaitSec: 172800
    tempWaitSec: 172800
    signedSinceChoiceSec: 345600
    recordAgeChoiceSec: 21686400
    workflowsStatus: OFF
  production:
    initialWaitSec: 172800
    tempWaitSec: 172800
    signedSinceChoiceSec: 345600
    recordAgeChoiceSec: 21686400
    workflowsStatus: OFF
  default:
    initialWaitSec: 300 # 5 mins
    tempWaitSec: 3600 # 1 hour
    signedSinceChoiceSec: 3
    recordAgeChoiceSec: 21686400 # 251 days
    workflowsStatus: ON

custom:
  project: ${env:PROJECT}
  serverlessTerminationProtection:
    stages: # Apply CloudFormation termination protection for these stages
      - master
      - val
      - production
  secretId: ${self:custom.project}/${sls:stage}/alerts

functions:
  workflowStarter:
    handler: handlers/workflowStarter.handler
    events:
      - stream:
          arn: ${param:mmdlTableStreamArn}
          startingPosition: LATEST
          maximumRetryAttempts: 0
    environment:
      stateMachineArn: !Ref MMDLAlertingStateMachine
      region: ${self:provider.region}
      errorsTopicArn: ${param:errorsTopicArn}
      workflowsStatus: ${param:workflowsStatus}
    maximumRetryAttempts: 0
  sendReport:
    handler: handlers/sendReport.handler
    timeout: 120
    environment:
      region: ${self:provider.region}
      mmdlTableName: ${param:mmdlTableName}
      seatoolTableName: ${param:seatoolTableName}
      errorsTopicArn: ${param:errorsTopicArn}
  seatoolRecordExist:
    handler: handlers/seatoolRecordExist.handler
    environment:
      region: ${self:provider.region}
      seatoolTableName: ${param:seatoolTableName}
      errorsTopicArn: ${param:errorsTopicArn}
  sendNoMatchAlert:
    handler: handlers/sendNoMatchAlert.handler
    environment:
      region: ${self:provider.region}
      project: ${self:custom.project}
      stage: ${sls:stage}
      sesLogGroupName: ${param:sesLogGroupName}
      errorsTopicArn: ${param:errorsTopicArn}
  getMmdlData:
    handler: handlers/getMmdlData.handler
    environment:
      region: ${self:provider.region}
      project: ${self:custom.project}
      stage: ${sls:stage}
      mmdlTableName: ${param:mmdlTableName}
      errorsTopicArn: ${param:errorsTopicArn}
  stopExecutions:
    handler: handlers/stopExecutions.handler
    environment:
      region: ${self:provider.region}
      stateMachineArn: !Ref MMDLAlertingStateMachine
resources:
  Resources:
    NoMatchStream:
      Type: AWS::Logs::LogStream
      Properties:
        LogGroupName: ${param:sesLogGroupName}
        LogStreamName: NOMATCH-MMDL
    NotFoundStream:
      Type: AWS::Logs::LogStream
      Properties:
        LogGroupName: ${param:sesLogGroupName}
        LogStreamName: NOTFOUND-MMDL
    StateMachineLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        LogGroupName: /aws/vendedlogs/states/${self:service}-${sls:stage}-alert
    StopExecutions:
      Type: Custom::StopExecutions
      Properties:
        ServiceToken: !GetAtt StopExecutionsLambdaFunction.Arn

stepFunctions:
  stateMachines:
    compareAlertFunc:
      name: ${self:service}-${sls:stage}-compare-alerting-mmdl
      id: MMDLAlertingStateMachine
      loggingConfig:
        level: ALL
        includeExecutionData: true
        destinations:
          - !GetAtt StateMachineLogGroup.Arn
      definition:
        Comment: "A State Machine to orchestrate a CMS alerting workflow for MMDL."
        StartAt: InitialWait
        States:
          InitialWait:
            Type: Wait
            Seconds: ${param:initialWaitSec}
            Next: GetMmdlDataTask
          GetMmdlDataTask:
            Type: Task
            Resource: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${self:service}-${sls:stage}-getMmdlData"
            Parameters:
              Payload.$: $
            Next: StatusSubmittedChoice
          StatusSubmittedChoice:
            Type: Choice
            Choices:
              - Variable: $.isStatusSubmitted
                BooleanEquals: true
                Next: DoesSeatoolRecordExistTask
              - Variable: $.isStatusSubmitted
                BooleanEquals: false
                Next: RecordAgeChoice
            Default: RecordAgeChoice
          DoesSeatoolRecordExistTask:
            Type: Task
            Resource: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${self:service}-${sls:stage}-seatoolRecordExist"
            Parameters:
              Payload.$: $
            Next: HandleSeatoolRecordExistChoice
          HandleSeatoolRecordExistChoice:
            Type: Choice
            Choices:
              - Variable: $.seatoolExist
                BooleanEquals: true
                Next: RecordAgeChoice # for now we are skipping the compare task
                # Next: CompareTask
              - Variable: $.seatoolExist
                BooleanEquals: false
                Next: SignedSinceChoice
            Default: SignedSinceChoice
          SignedSinceChoice:
            Type: Choice
            Choices:
              - And:
                  - Variable: $.secSinceMmdlSigned
                    IsPresent: true
                  - Variable: $.secSinceMmdlSigned
                    NumericGreaterThanEquals: ${param:signedSinceChoiceSec}
                  - Variable: $.mmdlSigned
                    BooleanEquals: true
                Next: SendNotExistTask
            Default: RecordAgeChoice
          SendNotExistTask:
            Type: Task
            Resource: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${self:service}-${sls:stage}-sendNoMatchAlert"
            Parameters:
              Payload.$: $
            Next: RecordAgeChoice
          RecordAgeChoice:
            Type: Choice
            Choices:
              - Variable: $.secSinceMmdlSigned
                NumericGreaterThanEquals: ${param:recordAgeChoiceSec}
                Next: LastLoopAMatchChoice
            Default: TempWait
          TempWait:
            Type: Wait
            Seconds: ${param:tempWaitSec}
            Next: GetMmdlDataTask
          LastLoopAMatchChoice:
            Type: Choice
            Choices:
              - And:
                  - Variable: $.match
                    IsPresent: true
                  - Variable: $.match
                    BooleanEquals: true
                Next: SuccessState
            Default: FailState
          SuccessState:
            Type: Succeed
          FailState:
            Type: Fail
